### PR TITLE
feat(CI): move from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by Helias**

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
@helias merge?

**Comment by Helias** [comment]
no because the build fail

**Comment by locus313** [comment]
@Helias I did some testing on with this workflow It will require the 2 open pr's I submitted to be merged get this working.
https://github.com/azerothcore/mod-solo-lfg/pull/7
https://github.com/azerothcore/mod-solo-lfg/pull/8
But here is a workflow I tested that worked in my test branch:

```
name: core-build
on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang6, clang9, clang10]
    runs-on: ubuntu-20.04
    name: ${{ matrix.compiler }}
    env:
      COMPILER: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'azerothcore/azerothcore-wotlk'
          ref: 'master'
          submodules: 'recursive'
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          path: 'modules/mod-solo-lfg'
      - name: Apply core patch
        run: git apply modules/mod-solo-lfg/lfg-solo.patch
      - name: Apply docker patch
        working-directory: ./modules/mod-solo-lfg
        run: git apply docker.patch        
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: /home/runner/.ccache
          key: ccache:${{ matrix.compiler }}:${{ github.ref }}:${{ github.sha }}
          restore-keys: |
            ccache:${{ matrix.compiler }}:${{ github.ref }}
            ccache:${{ matrix.compiler }}
      - name: Configure OS
        run: source ./apps/ci/ci-install.sh
        env:
          CONTINUOUS_INTEGRATION: true
      - name: Import db
        run: source ./apps/ci/ci-import-db.sh
      - name: Build
        run: source ./apps/ci/ci-compile.sh
      - name: Dry run
        run: source ./apps/ci/ci-worldserver-dry-run.sh
      - name: Check startup errors
        run: source ./apps/ci/ci-error-check.sh
```

**Comment by Helias** [comment]
Very good job :P

Hope to merge your PRs soon!

Anyways, I was wondering if for some values like "runs-on: ubuntu20.04" or "compiler" we could use some organizations github variables so if we change it once like with ubuntu 20.10 (but usually i prefer to use only ubuntu LTS version) we just need to change one variable value instead of the entire yml files in all modules repo.

Do you agree? we can do this next time that we need to edit the github action in all modules.

**Comment by Helias** [comment]
Moreover, @locus313 there are other modules where the github action do not work, if you can take a look at them would be really nice :P

Like these ones:
- https://github.com/azerothcore/mod-pvpscript/pull/2
- https://github.com/azerothcore/mod-npc-gambler/pull/6
- https://github.com/azerothcore/mod-phased-duels/pull/8

I don't remember if there are anymore

**Comment by locus313** [comment]
That is an interesting idea using a github organization variable. Do think that could be fine as long as we run a test build with the proposed new version before switching the variable. Would be much easier then having to update the workflows on each repo. :)
I agree, We should stick the the LTS versions. :)

Sure. I don't mind taking a look.

**Comment by locus313** [comment]
submit the updated workflow in a new pr:
https://github.com/azerothcore/mod-solo-lfg/pull/9
added you as a co-author @Helias

**Pull request closed without merging**
