### PR TITLE
fix(cpp): Remove Need for Patch Using New Hook in AC

### PR DESCRIPTION
**Pull request by LannyE**
A new hook (Debug Mode) has been added to AC that can be used by this module. https://github.com/azerothcore/azerothcore-wotlk/pull/5995
This removes the need for the patch.

Changes made:
- Updated the cpp to use the new IsTesting mode hook
- Updated the Readme to remove the patch information
- Deleted the patch file

To Test:
- Remove the patch from the AC code
- CMAKE 
- Recompile
- Use the "Looking for Group" tool in game while not in a group.

### CODE REVIEW

**Review by Gadeus — APPROVED** [review]
Tested with AC rev. 889182215ca5

**Comment by LannyE** [comment]
I had to do the GetOption fix to this module that I had to do to the other modules I updated today.

**Comment by LannyE** [comment]
Is this going to get merged?  Is there a problem?

**Review by Gadeus — APPROVED** [review]

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
> Is this going to get merged?  Is there a problem?

I am going to message shin about merging. For some reason i do not have the ability to merge on this module for whatever reason

**Review by locus313 — APPROVED** [review]

**Comment by locus313** [comment]
Thanks for this contribution @LannyE !

**Pull request merged**
