### PR TITLE
Docker and lfg-solo patches updated

### PR DESCRIPTION
**Pull request by febaut**
Doing the update again. I did a mess with the previous PRs  thats why I closed them.

- Closes https://github.com/azerothcore/mod-solo-lfg/issues/28
- Closes https://github.com/azerothcore/mod-solo-lfg/issues/26

### CODE REVIEW

**Review by nolt — APPROVED** [review]
Tested with AC rev a9a3bc9, module apply and works as intended,

**Comment by nolt** [comment]
@febaut
hope, you didn't delete your branch :)

**Comment by nolt** [comment]
This is outdated and can be closed i suppouse.

**Comment by pangolp** [comment]
Process to close this pull request, anyway, we are reviewing the code, in case someone reports an issue related to it, and we can get to use it in the future. Thanks for the input. And a thousand apologies for the elapsed time.

**Pull request closed without merging**
