### PR TITLE
[Possible Fix - Requires to be tested] Patch updated to current AzerothCore Source.

### PR DESCRIPTION
**Pull request by febaut**
This is a lfg-solo.patch file update.  

Aims to solve the issue: 

https://github.com/azerothcore/mod-solo-lfg/issues/28

Please test and give some feedback if necessary.

### CODE REVIEW

**Comment by nolt** [comment]
You have not needed tabs in 21 line 
```
git apply modules/mod-solo-lfg/lfg-solo.patch
modules/mod-solo-lfg/lfg-solo.patch:21: trailing whitespace, tab in indent.
		 if (!sLFGMgr->IsSoloLFG() && !allAnswered)	
error: corrupt patch at line 35
```

but even removing them, it still I'll get

```
error: corrupt patch at line 35
```

**Comment by febaut** [comment]
Humm, weird I applied the patch with 0 issues. I mean yeah it recognises the whitespaces but still work.

**Comment by nolt** [comment]
git apply modules/mod-solo-lfg/lfg-solo.patch
```

modules/mod-solo-lfg/lfg-solo.patch:21: tab in indent.
	if (!sLFGMgr->IsSoloLFG() && !allAnswered)
modules/mod-solo-lfg/lfg-solo.patch:44: tab in indent.
	 /// Toggle LFG in debug mode
modules/mod-solo-lfg/lfg-solo.patch:55: tab in indent.
	 bool m_isSoloLFG;                                  ///< solo lfg
modules/mod-solo-lfg/lfg-solo.patch:70: tab in indent.
	 if (!sLFGMgr->IsSoloLFG() && numPlayers != MAXGROUPSIZE) // solo lfg
modules/mod-solo-lfg/lfg-solo.patch:71: tab in indent.
	  {
error: patch failed: src/server/game/DungeonFinding/LFGMgr.cpp:39
error: src/server/game/DungeonFinding/LFGMgr.cpp: patch does not apply
error: patch failed: src/server/game/DungeonFinding/LFGMgr.h:553
error: src/server/game/DungeonFinding/LFGMgr.h: patch does not apply
error: patch failed: src/server/game/DungeonFinding/LFGQueue.cpp:289
error: src/server/game/DungeonFinding/LFGQueue.cpp: patch does not apply
```

**Comment by nolt** [comment]
@febaut any updates on this?

**Pull request closed without merging**
